<?php

/**
 * Implements hook_form_alter().
 */
function module_whereis_form_alter(&$form, &$form_state, $form_id) {
  // Check for this so that this info is not displayed on the "Some required modules must be enabled" confirmation page
  if ('system_modules' == $form_id) {
    $locations = db_query("SELECT name, filename FROM {system} WHERE type = 'module' ORDER BY name")->fetchAllKeyed();
    foreach ($locations as $name => $location) {
      if (isset($form['modules'][$name])) {
        $desc = $form['modules'][$name]['description']['#markup'];
        $form['modules'][$name]['description']['#markup'] = $desc . '<div style="font-size: 10px;"> ' . t('Location: ') . $location . '</div>';
      }
    }
  }
}